language: python
python:
  - "2.7"
  - "3.5"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python tests/run_search.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then python tests/run_search.py; fi
