language: python

python:
  - "2.7"
  - "3.5"

before_script:
  - pip install coverage codecov
  - pip install -r requirements.txt

script:
  - python --version
  - export PYTHONPATH=$PWD/:$PYTHONPATH
  - coverage run tests/test_run.py
  - coverage combine
  - codecov
