language: python
sudo: required
python:
  - "2.7"
  - "3.5"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
# command to install dependencies
before_script:
  - sudo apt-get install -qq python-numpy
  - pip install -r requirements.txt
install:
    make build
# command to run tests
script:
  - export PYTHONPATH=$PWD/:$PYTHONPATH
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python tests/run_search.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then python tests/run_search.py; fi
